name: Validate action typings

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validate-typings:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: typesafegithub/github-actions-typing@v1
