name: Test Git Secret Action

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  git_secret_job:
    runs-on: ubuntu-latest
    name: Reveal Secrets
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy Dockerfile over template
        run: |
          cp -f devops/Dockerfile Dockerfile

      - name: Git Secret Reveal Step
        id: git-secret
        uses: ./
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Assert the secret Exists
        run: |
          SECRET=$(cat .env | grep "ACTION")
          if [ "$SECRET" = "ACTION=git-secret-action" ]
          then
            exit 0
          else
            exit 1
          fi

  git_secret_passphrase_job:
    runs-on: ubuntu-latest
    name: Reveal Secrets with Passphrase
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy Dockerfile over template
        run: |
          cp -f devops/Dockerfile Dockerfile

      - name: Git Secret Reveal Step
        id: git-secret
        uses: ./
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_LOCKED_KEY }}
          gpg-private-key-passphrase: ${{ secrets.GPG_PRIVATE_LOCKED_PASSPHRASE }}

      - name: Assert the secret Exists
        run: |
          SECRET=$(cat .env | grep "ACTION")
          if [ "$SECRET" = "ACTION=git-secret-action" ]
          then
            exit 0
          else
            exit 1
          fi
